[omnibus][packaging] removing most of the package scripting for now. Bunch of TODOs

diff --git a/omnibus/package-scripts/agent/prerm b/omnibus/package-scripts/agent/prerm
--- a/omnibus/package-scripts/agent/prerm
+++ b/omnibus/package-scripts/agent/prerm
@@ -4,67 +4,38 @@
 #
 # .deb: STEP 1 of 5
 # .rpm: STEP 4 of 6
-
-KNOWN_DISTRIBUTION="(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon|Arista|SUSE)"
-DISTRIBUTION=$(lsb_release -d 2>/dev/null | grep -Eo $KNOWN_DISTRIBUTION  || grep -Eo $KNOWN_DISTRIBUTION /etc/issue 2>/dev/null || grep -Eo $KNOWN_DISTRIBUTION /etc/Eos-release 2>/dev/null || grep -m1 -Eo $KNOWN_DISTRIBUTION /etc/os-release 2>/dev/null || uname -s)
+# .bff: STEP ? of ? (TODO)
 
 INSTALL_DIR=/opt/datadog-agent
 SERVICE_NAME=datadog-agent
 
-if [ -f "/etc/debian_version" ] || [ "$DISTRIBUTION" = "Debian" ] || [ "$DISTRIBUTION" = "Ubuntu" ]; then
-    DISTRIBUTION_FAMILY="Debian"
-fi
 
+# TODO: fix this because there's no systemd or upstart on AIX
+#       just keeping the functions around for reference.
 stop_agent()
 {
     # Stop an already running agent
-    # Only supports systemd and upstart
     if command -v systemctl >/dev/null 2>&1; then
-        systemctl stop $SERVICE_NAME-process || true
-        systemctl stop $SERVICE_NAME-network || true
-        systemctl stop $SERVICE_NAME-trace || true
         systemctl stop $SERVICE_NAME || true
     elif command -v initctl >/dev/null 2>&1; then
-        initctl stop $SERVICE_NAME-process || true
-        initctl stop $SERVICE_NAME-network || true
-        initctl stop $SERVICE_NAME-trace || true
         initctl stop $SERVICE_NAME || true
-    elif [ "$DISTRIBUTION_FAMILY" = "Debian" ]; then
-        if command -v service >/dev/null 2>&1; then
-            service $SERVICE_NAME-process stop || true
-            service $SERVICE_NAME-network stop || true
-            service $SERVICE_NAME-trace stop || true
-            service $SERVICE_NAME stop || true
-        else
-            echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd, upstart and sysvinit."
-        fi
     else
         echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
     fi
 }
 
+# TODO: fix this because there's no systemd or upstart on AIX
+#       just keeping the functions around for reference.
 deregister_agent()
 {
     # Disable agent start on system boot
     # Only supports systemd and upstart
     if command -v systemctl >/dev/null 2>&1; then
         # Force systemd to ignore the sysvinit scripts. Only cosmetic, remove some irrelevant warnings during upgrade
-        SYSTEMCTL_SKIP_SYSV=true systemctl disable $SERVICE_NAME-process || true
-        SYSTEMCTL_SKIP_SYSV=true systemctl disable $SERVICE_NAME-network || true
-        SYSTEMCTL_SKIP_SYSV=true systemctl disable $SERVICE_NAME-trace || true
         SYSTEMCTL_SKIP_SYSV=true systemctl disable $SERVICE_NAME || true
     elif command -v initctl >/dev/null 2>&1; then
         # Nothing to do, this is defined directly in the upstart job file
         :
-    elif [ "$DISTRIBUTION_FAMILY" = "Debian" ]; then
-        if command -v update-rc.d >/dev/null 2>&1; then
-            update-rc.d -f $SERVICE_NAME-process remove || true
-            update-rc.d -f $SERVICE_NAME-network remove || true
-            update-rc.d -f $SERVICE_NAME-trace remove || true
-            update-rc.d -f $SERVICE_NAME remove || true
-        else
-            echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd, upstart and sysvinit."
-        fi
     else
         echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
     fi
@@ -79,32 +50,29 @@ remove_py_compiled_files()
     fi
 }
 
-if [ -f "/etc/debian_version" ] || [ "$DISTRIBUTION" = "Debian" ] || [ "$DISTRIBUTION" = "Ubuntu" ]; then
-    stop_agent
-    deregister_agent
-    remove_py_compiled_files
-elif [ -f "/etc/redhat-release" ] || [ -f "/etc/system-release" ] || [ -f "/etc/SuSE-release" ] || [ "$DISTRIBUTION" = "RedHat" ] || [ "$DISTRIBUTION" = "CentOS" ] || [ "$DISTRIBUTION" = "openSUSE" ] || [ "$DISTRIBUTION" = "Amazon" ] || [ "$DISTRIBUTION" = "SUSE" ] || [ "$DISTRIBUTION" = "Arista" ]; then
-    stop_agent
-    deregister_agent
+# TODO: make sure this all makes sense on AIX. 
+#       Already removed the debian relevant portion keeping
+#       the RPM bits (just because RPMs are supported on AIX).
+#      
+#       FIGURE OUT WHAT MAKES SENSE ON AIX HERE.
 
-    case "$*" in
-        0)
-            # We're uninstalling.
-            remove_py_compiled_files
-        ;;
-        1)
-            # We're upgrading.
-            # The preinst script has taken care of removing the .pyc/.pyo files
-        ;;
-        *)
-        ;;
-    esac
-else
-    echo "[ ${Red}FAILED ${RCol}]\tYour system is currently not supported by this script.";
-fi
+## stop_agent
+## deregister_agent
+## 
+## case "$*" in
+##     0)
+##         # We're uninstalling.
+##         remove_py_compiled_files
+##     ;;
+##     1)
+##         # We're upgrading.
+##         # The preinst script has taken care of removing the .pyc/.pyo files
+##     ;;
+##     *)
+##     ;;
+## esac
 
 # Delete all .pyc files in the `agent/` and the `bin/agent/dist` dirs
-find $INSTALL_DIR/agent -name '*.py[co]' -type f -delete || echo "Unable to delete .pyc files in $INSTALL_DIR/agent"
-find $INSTALL_DIR/bin/agent/dist -name '*.py[co]' -type f -delete || echo "Unable to delete .pyc files in $INSTALL_DIR/bin/agent/dist"
+# find $INSTALL_DIR/agent -name '*.py[co]' -type f -delete || echo "Unable to delete .pyc files in $INSTALL_DIR/agent"
 
 exit 0
