[installer] setup python if necessary + added robustness (#45)
* [rpms] adding rpm dependencies

* [installer] adding installer steps

* [installer] fixing unpack

* [installer] fixing unpack

* [installer] bashifying script

* [installer] remove pipe, already doing process substition at end of loop

* [rpms] removing pysqlite dependency

* [installer] fixing multiple issues

* [deps] moving psutil to environment deps dir

* [installer] some more cleanup

* [installed] verify space during decompress phase

* [installer] check size compliance with `bc`

* [process][tests] ignore `datadog.agent.running` metric

* [installer] install bundled integrations - non-core

[installer] fix decompress script

* [installer] drop dependency on bash - default is ksh

* [installer] use requirements as a constraints file

* [installer] adding cffi bff - required by py cffi

* [packaging] updating installer to install bundled filesets

* [supervisor] updating entries

* [README] updating documentation

* [deps][cffi] updated wheels - keep these

* [deps] adding cffi wheel for 7.2

* [README] updating further

diff --git a/packaging/decompress b/packaging/decompress
--- a/packaging/decompress
+++ b/packaging/decompress
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 set -e
 
@@ -8,6 +8,35 @@ echo ""
 
 export TMPDIR="/tmp/datadog-aix-installer.$$"
 AGENT_PATH="/opt/datadog/datadog-unix-agent"
+
+if [[ "$(id -u)" != "0" ]]
+then
+    echo "The installer should be run as a root"
+    exit 1
+fi
+
+#Check if /tmp has enough space to untar (150MB shouldn't need much more) 
+#Extracting rpm packages.
+# 45 MB for rpm.rte and 54 MB for yum_bundle.tar, 50 MB for rpm packages extracted.
+
+typeset -i total_req=`echo "(150)" | bc`
+tmp_free=$(df -m /tmp | sed -e /Filesystem/d | awk '{print $3}')
+if [[ "$(echo "if ($tmp_free < $total_req) 1" | bc)" -eq 1 ]];
+then
+    echo "Please make sure /tmp has at least 150MB of free space to proceed..."
+    exit 1
+fi
+
+#Check if /opt is having enough space to install the packages from yum_bundle.
+#Currently we need around 300MB of free space in /opt filesystem (might be less).
+typeset -i total_opt=`echo "(300)" | bc`
+opt_free=$(df -m /opt | sed -e /Filesystem/d | awk '{print $3}')
+if [[ "$(echo "if ($opt_free < $total_opt) 1" | bc)" -eq 1 ]];
+then
+    echo "Total free space required for /opt is around 300 MB."
+    echo "Please increase the /opt space and retry."
+    exit 1
+fi
 
 mkdir $TMPDIR
 
diff --git a/packaging/payload/installer b/packaging/payload/installer
--- a/packaging/payload/installer
+++ b/packaging/payload/installer
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 YAML_BACKUP=
 ETC_BACKUP=
@@ -6,7 +6,208 @@ PSUTIL_WHEEL=
 AIX_VERSION=$(uname -v)
 AIX_RELEASE=$(uname -r)
 
-install() {
+#Compares the two packages version number
+function cmp_version {
+    large=$(echo  ${pkgcurr[1]} ${pkgversion[$index]}  | \
+        awk '{ split($1, a, ".");
+    split($2, b, ".");
+    x = 0;
+    for (i = 1; i <= 4; i++)
+        if (a[i] < b[i]) {
+            x = 3;
+            break;
+        } else if (a[i] > b[i]) {
+        x = 2;
+        break;
+    }
+    print x;
+}')
+return $large
+}
+
+#Compares the two packages release number
+function cmp_release {
+    if [[ $1 < $2 ]]
+    then
+        return 3
+    elif [[ $1 > $2 ]]
+    then
+        return 2
+    elif [[ $1 == $2 ]]
+    then
+        return 1
+    fi
+}
+
+function install_filesets {
+    cd $1/deps/bffs
+    echo "\n"
+    echo "Installing required fileset..."
+    installp -aXYgd . -e $TMPDIR/install.log all
+    RET=$?
+
+    cd -
+    return $RET
+}
+
+function install_python {
+    #Check if some packages are already installed from the yum_bundle.
+    
+    cd $1/deps/rpms
+
+    echo "\n"
+    echo "Checking if any of the rpms are already installed...\n"
+    set -A pkgname
+    set -A pkgversion
+    set -A pkgrelease
+    set -A inst_list
+
+    ls *.rpm | while read rpm_file
+    do
+        pkgname[${#pkgname[*]}]=`rpm -qp --qf "%{NAME}" $rpm_file`
+        pkgversion[${#pkgversion[*]}]=`rpm -qp --qf "%{VERSION}" $rpm_file`
+        pkgrelease[${#pkgrelease[*]}]=`rpm -qp --qf "%{RELEASE}" $rpm_file`
+    done
+
+    let "index=0"
+    for pk in ${pkgname[@]}
+    do
+        # We need to match exact package name, as we might have packages like python python-devel etc..
+        # Packages name will be followed by the version number with "-" as a seperator.
+
+        set -A pkgcurr ""
+        let "flag=0"
+        rpm_file=`ls *.rpm | grep  "^$pk-[0-9]"`
+        line=`rpm -qa | grep "^$pk-[0-9]"`
+
+        if [[ ! -z $line ]]
+        then 
+            # Special care must be taken for packages name having more than one fields.
+            # For example python-devel
+            oldIFS=$IFS
+            IFS='-'
+            set -A name_ver $line
+            IFS=$oldIFS
+            count=`echo ${#name_ver[@]}` #Count number of fields in a package. 
+            # Exclude release, version field plus array index starts with 0.
+            let "i=$count-3"
+        
+            if [[ $i -eq 0 ]]
+            then
+                name=`echo "${name_ver[0]}"`
+            elif [[ $i -eq 1 ]]
+            then
+                name=`echo "${name_ver[0]}-${name_ver[1]}"`
+            elif [[ $i -eq 2 ]]
+            then
+                name=`echo "${name_ver[0]}-${name_ver[1]}-${name_ver[2]}"`
+            elif [[ $i -eq 3 ]]
+            then
+                name=`echo "${name_ver[0]}-${name_ver[1]}-${name_ver[2]}-${name_ver[3]}"`
+            else
+                echo "Package name more than 4 fields"
+            fi
+
+            #To get version exclude release field plus 0 index array.
+            let "j=$count-2"
+            ver=`echo ${name_ver[$j]}`
+         
+            # Now set the name version field.
+            set -A pkgtest "$name" "$ver"
+        elif [[ -z $line ]]
+        then
+            set -A pkgtest "$line"
+        fi
+
+        #get the release field from the installed package.
+        release=`rpm -qa | grep "^$pk-[0-9]" | awk -F '-' {'print $NF'} | awk -F '.' {'print $1'}`
+        # If package from yum_bundle is installed.
+        if [[ ${pkgtest[0]} == $pk ]]
+        then
+            set -A pkcurr "$name" "$ver"
+            #compare versions of installed package & from the yum bundle.
+            cmp_version ${pkgtest[1]} ${pkgversion[$index]}
+            rc=$?
+            if [[ $rc -eq 3 ]]
+            then
+                let "flag=3" #Lower version already installed
+            elif [[ $rc -eq 2 ]]
+            then
+                let "flag=2" # Higher version already installed
+            elif [[ $rc -eq 0 ]]
+            then
+                # If version numbers are same then compare the release of packages.
+                if [[ ${pkgtest[1]} == ${pkgversion[$index]} ]]
+                then
+                    cmp_release $release ${pkgrelease[$index]}
+                    rc=$?
+                    if [[ $rc -eq 3 ]]
+                    then
+                        let "flag=3"
+                    elif [[ $rc -eq 2 ]]
+                    then
+                        let "flag=2" 
+                    elif [[ $rc -eq 1 ]]
+                    then
+                        let "flag=1"   # Exact version installed
+                    fi
+               fi
+           fi
+        fi
+      
+        if [[ "$flag" -eq 1 ]]
+        then
+            echo "Package ${pkgcurr[0]}-${pkgcurr[1]}-$release is already installed"
+            let "index=index+1"
+            continue;
+        elif [[ "$flag" -eq 2 ]]
+        then
+            echo "Skipping ${pkgname[$index]}-${pkgversion[$index]}-${pkgrelease[$index]} as higher version is installed already."
+            echo "Please make sure these packages are from toolbox as there is no gurantee that"
+            echo "third party packages may be compatible with toolbox packages.\n"
+            let "index=index+1"
+            continue;
+        elif [ "$flag" -eq 3 ]
+        then
+            echo "${pkgtest[0]}-${pkgtest[1]}-$release is installed. Will be updated to ${pkgname[$index]}-${pkgversion[$index]}-${pkgrelease[$index]} ...."
+            inst_list[${#inst_list[*]}+1]=$rpm_file
+            let "index=index+1"
+            continue;	
+        elif [ "$flag" -eq 0 ]
+        then
+            echo "${pkgname[$index]}-${pkgversion[$index]}-${pkgrelease[$index]} will be installed ...."
+            inst_list[${#inst_list[*]}+1]=$rpm_file
+            let "index=index+1"
+            continue;
+        fi
+    done
+
+    if [[ ${#inst_list[@]} -eq 0 ]]
+    then
+        echo "\nYum and all it's dependencies are installed already..."
+        cd - >/dev/null 2>&1
+        return 1
+    fi
+
+    echo "\nInstalling the packages.\n"
+    rpm -Uvh ${inst_list[@]}
+
+    if [[ $? -eq 0 ]]
+    then
+        echo "\033[1;32mYum installed Successfully.... \033[m"
+    elif [[ $? -ne 0 ]]
+    then
+       echo "\033[1;31mYum installation failed... \033[m" 
+       echo "If the failure was due space requirement then increase the /opt space and please retry"
+       echo "Other reason of failure could be mixing of Toolbox packages and packages from other sources."
+        cd - >/dev/null 2>&1
+       return 1
+    fi
+
+    cd - >/dev/null 2>&1
+}
+
+function unpack {
     echo "Unpacking..."
     gunzip ./archive.tar.gz
     tar xf ./archive.tar
@@ -15,24 +216,26 @@ install() {
     PARENT_DIR=$(dirname $1)
     mkdir -p $PARENT_DIR
     find . -type d -name 'DataDog-datadog-unix-agent*' 2>/dev/null | head -n 1 | xargs -t -I {} cp -R {} $1
+}
 
+function install {
     cd $1
 
     set +e
     echo "preparing system-wide python..."
-    echo -e "\tchecking for pip..."
-    python -c "import pip"
+    echo "\tchecking for pip..."
+    python -c "import pip" >/dev/null 2>&1
     if [ $? -ne 0 ]; then
         echo "\t\tpip unavailable - installing..."
-        python get-pip.py --no-index --find-links=$(cd $1; pwd)/deps/sys/
+        python $(cd $1; pwd)/deps/sys/get-pip.py --no-index --find-links=$(cd $1; pwd)/deps/sys/
     else
         echo "pip already installed, will use existing system pip"
     fi
 
-    declare -a deps=("setuptools" "wheel" "virtualenv")
+    set -A deps "setuptools" "wheel" "virtualenv"
     for dep in "${deps[@]}"; do
-        echo -e "\tchecking for $dep..."
-        python -c "import $dep"
+        echo "\tchecking for $dep..."
+        python -c "import $dep" >/dev/null 2>&1
         if [ $? -ne 0 ]; then
             echo "\t\t$dep unavailable - installing..."
             python -m pip install --no-index --find-links file://$(cd $1; pwd)/deps/sys/ $dep 
@@ -45,37 +248,32 @@ install() {
 
     echo "building virtual environment from scratch..."
     python -m virtualenv --python python2.7 venv
-    source ./venv/bin/activate
+
+    # we need to +e due to the korn shell
+    set +e
+    . ./venv/bin/activate
+    set -e
 
     echo "installing python dependencies..."
-    pip install ./deps/psutil/$PSUTIL_WHEEL
     pip install -r requirements.txt --no-index --find-links file://$(cd $1; pwd)/deps/env/
+
+    echo "installing bundled (non-core) checks..."
+    pip install -c requirements.txt --no-index --find-links file://$(cd $1; pwd)/deps/env/ $(cd $1; pwd)/checks/bundled/datadog_checks_base
+    for check in $(ls -d $(cd $1; pwd)/checks/bundled/* | grep -iv 'datadog_checks_base');
+    do
+        echo "installing $(basename $check)..."
+        pip install -c requirements.txt --no-index --find-links file://$(cd $1; pwd)/deps/env/ $check
+    done
     cd - 
+
 
     echo "finalizing directory structure defaults..."
     mkdir -p $1/var/log/datadog
     mkdir -p $1/etc/datadog-agent/conf.d
 }
 
-set -e
 
 echo "Installation for $AIX_VERSION.$AIX_RELEASE..."
-
-case "$AIX_VERSION" in
-    6|7) 
-        M=
-        python -c "import platform; print platform.architecture()[0]" | grep '64bit'
-        if [ $? -eq 0 ]; then
-            M='m'
-        fi
-        PSUTIL_WHEEL="psutil-5.4.6-cp27-cp27${M}-aix_${AIX_VERSION}_${AIX_RELEASE}.whl"
-        ;;
-    *) 
-        echo "unsupported AIX version: $AIX_VERSION.$AIX_RELEASE - bailing out"
-        exit 1
-        ;;
-esac
-
 
 echo "Running Installer..."
 if [ -e $1/datadog.yaml ]; then
@@ -90,17 +288,42 @@ fi
 
 if [ -d $1 ]; then
     echo "Previous installation found, it will be overwritten (existing configuration will be preserved however)."
-    read -p "Are you sure you want to continue? " -n 1 -r
-    echo 
-    if [[ $REPLY =~ ^[Yy]$ ]]
+    echo "Are you sure you want to continue (Yy/Nn) ?"
+    read RESP 
+
+    if [[ "$(echo $RESP | grep -E '[Yy]')" == "" ]];
     then
-        rm -rf $1
-    else
         echo "will not continue with installation, exiting..."
         exit 0
+    else
+        rm -rf $1
     fi
 fi
 
+unpack $1
+
+install_filesets $1
+if [ $? -ne -0 ];
+then
+    echo "There was a problem installing the required filesets..."
+    exit 1
+fi
+
+which python >/dev/null 2>&1
+if [ $? -ne 0 ];
+then
+    echo "install python via rpm..."
+    install_python $1
+    if [ $? -ne 0 ];
+    then
+        echo "problem installing python..."
+        exit 1
+    fi
+fi
+
+set -e
+
+echo "setting up..."
 install $1
 
 if [ -e $TMPDIR/datadog.yaml ]; then
